Develop jiaxing
yuxiao-qin/scientific_research_with_python_demo pull request #4
Opened 2023-02-12 10:10 UTC by applepie1026

a test of pull request

2023-02-14 04:16 UTC, yuxiao-qin requested changes

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    return (phase + np.pi) % (2 * np.pi) - np.pi# 缠绕相位,测试，测试,test
请使用有意义的注释。

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    noise_phase = generate_phase_noise(noise_level)*4*np.pi/WAVELENGTH
*4*np.pi/WAVELENGTH 的逻辑应该放到 generate_phase_noise() 里面。

一个函数应该包括一个完整的功能，转换到 phase 的功能是 `generate_phase_noise` 的一部分。

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    Btemp=temporal_baseline*time_range
这个名字起得不好。应该是：

```python
temporal_baseline = ...
temporal_samples = temporal_baseline * time_range
```

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    B_normal=300#[unit:m]
```python
normal_baseline = ... 
```

另外，注意，每幅影像的 normal baseline 实际上是不一样的，不应该是一个常数

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    H=780000# satellite vertical height[m]
“#” 应当空两格

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    theta=23*np.pi/180
`theta` 名字有点模糊，这里建议用 `incidence_angle`

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    Bn=4*np.pi*B_normal/(WAVELENGTH*R*np.sin(theta))
这个地方不应该是 Bn，应该叫 "h2ph_coefficient"，或者这个可以简称 "h2ph_coef"

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    Search_space=np.mat(np.arange(-Nsearch*step,Nsearch*step,step))
请用 link_with_underscore 的命名方法

2023-02-14 04:16 UTC, yuxiao-qin commented on scientific_research_with_python_demo/main.py
> +    search_space=np.kron(phase_search1,np.ones(1,num_serach[1]))+np.kron(np.ones(1,num_serach[0]),phase_serach2)
这个地方我们要再讨论一下

2023-02-22 01:54 UTC, applepie1026 commented
1.the prograss of parameters estimation by using best_index
2. request more information about ind2sub by python
3.tests about construct paramters search_space
and maximum are done
see the commit 
["7bb0b8672297620ce937f72849f8db302647332b"](https://github.com/yuxiao-qin/scientific_research_with_python_demo/pull/4/commits/7bb0b8672297620ce937f72849f8db302647332b)
@yuxiao-qin

2023-02-22 02:03 UTC, applepie1026 reviewed
1.the prograss of parameters estimation by using best_index
2. request more information about ind2sub by python
3.tests about construct paramters search_space
and maximum are done

2023-03-06 02:06 UTC, merged